# Generated by Django 4.2.5 on 2023-09-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0009_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
