# Generated by Django 4.2.5 on 2023-09-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0011_veiculo_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='nome',
            new_name='descricao',
        ),
    ]
