# Generated by Django 4.2.5 on 2023-09-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0013_rename_ano_fundacao_marca_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
